### PR TITLE
Lastpass review

### PR DESCRIPTION
**Pull request by michielbdejong**
Proposing class B.

Summary will look like this:
lastpass-summary

When you click on "More details":

lastpass-full-1

and scroll:

lastpass-full-2

and scroll:

lastpass-full-3

and scroll:

lastpass-full-4

and scroll:

lastpass-full-5

and scroll, finally:

lastpass-full-6

### CODE REVIEW

**Comment by piks3l** [comment]
If it's good for @hugoroy , I'm good too :)

**Comment by michielbdejong** [comment]
Will wait for Hugo's review before merging.

**Comment by michielbdejong** [comment]
This review was still done with my "hacky" curator script, I'll now try to do the WhatsApp review using a local instance of the official Tosdr2 application, running on my own laptop

**Comment by hugoroy** [comment]
I have  comments on 2 points:

- the one about treating IP addresses as personal info: this is the law in the EU, so there's no way around that,  otherwise it would be illegal in the EU (so they don't really have a choice). Giving them good points for that is weird.

- the one about sharing data to develop products: It doesn't seem to be reflected correctly in the title which only talks about sharing with law enforcement.

**Comment by olgagkot** [comment]
Hey, glad to make my first comment!
Since I have not followed the discussion from the beginning and I am still adapting to your work flows, I don't have much to say, plus feel free to ignore my comments if they were part of previous discussions: 
1. For the IP addresses, as Hugo said, I agree, but I still think it is good to say "bravo" for integrating the EU law in their ToS. (If not giving them thumbs up, it would still be nice to have it as a neutral mention).
2. Why two different paragraphs for the sudden change of terms?  I can imagine due to the need of putting emphasis on two different things, but possibly they could still be combined in one para ( same for the termination of services and no compensation ).
3. I see that LP follows some of the DP principles to an extent, but is there any info about how the data subject itself could withdraw or access the stored data ? ( See: information is shared in compliance with law enforcement ) From what I checked in their privacy statement, not really.. 
4. And something small: in the para for the publicly published emails, I think by accident,  "we" was used instead of "they" when referring to LP.  Thanks! And as previously stated, if it's good for @hugoroy , it is good for me, too..  :)

**Comment by michielbdejong** [comment]
>  treating IP addresses as personal info: this is the law in the EU

The way I understand it from https://en.wikipedia.org/wiki/Data_Protection_Directive, under the data protection act it's not allowed to record IP addresses of website visitors without their consent. However, when users 'tick the box and say they agree', this would allow LastPass, even in the EU, to track a user's IP addresses. They would just not be allowed to track users who haven't ticked the "I agree" or the "Yes, please use cookies" consent forms

**Comment by michielbdejong** [comment]
Re Olga's third point:

> I see that LP follows some of the DP principles to an extent, but is there any info about how the data subject itself could withdraw or access the stored data ? ( See: information is shared in compliance with law enforcement ) From what I checked in their privacy statement, not really..

DP is "Data Protection", right? I think you can remove your account to withdraw the stored data (if it were impossible to delete your account, there would be bad point about that). I'm not sure about accessing the data they have stored about you, we should maybe check that for all services and make it part of the checklist, I made a follow-up issue about that: https://github.com/tosdr/tosdr-build/issues/46

**Comment by michielbdejong** [comment]
I'll merge this pull request to the master branch now, but wait a bit longer before pushing it to the live site.

If we find more issues we can continue to improve this review in the master branch, both before and after it's published onto the site.

**Comment by michielbdejong** [comment]
Thanks everybody for the improvements!

**Pull request merged**
