### PR TITLE
Display case title and quote text as points of a service review

### PR DESCRIPTION
**Pull request by michielbdejong**
* always use the case title instead of the (custom) point title
* instead of point.tosdr.tldr (or point.analysis, as it's called in Phoenix), use point.quoteText
* link to phoenix instead of to Google Groups

### CODE REVIEW

**Comment by michielbdejong** [comment]
There's a branch on https://github.com/tosdr/tosdr.org with the same branch name. It looks like this:
screenshot from 2018-07-05 15-29-56

**Comment by Vinnl** [comment]
Does this make it so that only services with annotations are shown?

**Comment by michielbdejong** [comment]
yes

**Comment by michielbdejong** [comment]
Continued in https://github.com/tosdr/tosdr.org/pull/193

**Pull request closed without merging**
