### PR TITLE
reference Service or ServicePoint through GET params, amended

### PR DESCRIPTION
**Pull request by sdailey**

### CODE REVIEW

**Comment by sdailey** [comment]
Code for commit No 22 -  run in Chrome, Firefox, Safari, and emulated mobile environments without any issues.

**Comment by hugoroy** [comment]
@michielbdejong can you deploy on 5apps? My local repo isn't in a good state right now

**Comment by michielbdejong** [comment]
ok! this will be included in the next deploy. thanks!

**Comment by hugoroy** [comment]
Can you deploy @michielbdejong ?

**Comment by michielbdejong** [comment]
Deployed. Thanks again @sdailey for this contribution.

Btw, @Vinnl the grunt build is working well, funny running into you twice this week in Utrecht! :)
@hugoroy see you next week in Paris! :)

**Comment by hugoroy** [comment]
@sdailey : it would be awesome if you could write a blog post about the extension so we can publish your post on blog.tosdr.org and announce your extension :-) What do you think?

**Comment by sdailey** [comment]
@hugoroy Awesome idea - I'd be honored to, thanks!  I'm currently on a road trip that will wrap up next week, so I'll work on having something simple within a week!  :)

**Comment by sdailey** [comment]
@hugoroy I have updated my blog post here http://www.fixpunk.com/2015/04/28/broccoli-tosdr/!  let me know if that works (I see other posts on ToSDR's blog link to the author's site). If it does - then let me know if there's anything else i can do to help. :)

**Comment by hugoroy** [comment]
Yes, I'll post that some time this week, see https://github.com/tosdr/blog/ 

Thanks

**Pull request merged**
