### PR TITLE
[fix] remove flattr references by opencollective references through bulk replace

### PR DESCRIPTION
**Pull request by evilcel3ri**
Fixing https://github.com/tosdr/tosdr.org/issues/189

### CODE REVIEW

**Comment by Vinnl** [comment]
(Reminder that we have [tosdr-static](https://github.com/tosdr/tosdr-static) ([staging env](https://vinnl.gitlab.io/tosdr-static/)) where common elements like [header links](https://github.com/tosdr/tosdr-static/blob/master/src/App.tsx#L37) are automatically included in every header. It's in relatively good state, and mostly needs a review for relevant content.)

**Comment by piks3l** [comment]
Oh okay, I'm very confused by the structure of the static website... Should we do something about it, or is it just me ?

**Comment by michielbdejong** [comment]
@christalib sorry, can you run this search/replace again on https://github.com/tosdr/tosdr.org?

**Comment by michielbdejong** [comment]
@christalib can this be closed?

**Comment by evilcel3ri** [comment]
> @christalib can this be closed?

Well, we still have Flattr referenced on the [`about` page](https://tosdr.org/about.html), api.html, contribute.html... of the tosdr.org website. So I don't think we should close this...

edit: ah, but I didn't saw we moved that to a new repo. I'll do the change on the new part. Closing this.

**Pull request closed without merging**
