### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by piks3l**
* Fixing Flattr broken link
* Fixing Blog broken footer link
* Removing the code from the campaign

### CODE REVIEW

**Comment by piks3l** [comment]
Hey @Vinnl do you think you can merge and deploy this one ? Thanks ! (we are still looking for the credentials that will allow me to have access to the deployment of 5apps... ahah!)

**Comment by Vinnl** [comment]
Oh haha, I saw that - I just figured that someone more involved would take a look at it (might've been discussed in the Signal group). I'll have a look.

**Comment by piks3l** [comment]
Thanks <3 !  About that, do you want access to the Signal group ? There isn't much discussed other that was is already on the mailing list, but I think  it's useful for some quick and operational things

**Comment by Vinnl** [comment]
It's building right now. And sure, guess it can't hurt - will at least make it easier for you to ping me if you need a build ;)

**Comment by piks3l** [comment]
I'll get in touch by email :)

**Pull request merged**
