### PR TITLE
Update for campaign

### PR DESCRIPTION
**Pull request by piks3l**
Adding some modification for the campaign. Quick 'n dirty but main info is there

### CODE REVIEW

**Comment by Vinnl** [comment]
Not sure if it's my place to approve, but it looks good to me in any case :P Many points have had their closing newlines removed though, not sure if that was your intention?

**Comment by piks3l** [comment]
Errr... I really just follow the instruction. I don't understood the whole architecture of the website, the test and stuff. 

It looks like it works, we just need to send it into production and I don't have the authorizations :/

**Comment by Vinnl** [comment]
Then it's probably the result of your operating or something like that - it'll probably be fine. It looks like I have permissions to deploy as well, but given my limited involvement I'm not comfortable using them on my own accord. In other words: you tell me if I should deploy this or whether it's best to wait for Michiel :)

**Comment by piks3l** [comment]
Ok you have 5apps auth? Then, I recall Michiel told me he was on holidays and we are launching a crowdfunding campaign in 4 hours. So i'd say, go for it. I'll take responsibility for it if anything goes wrong. 

Thank you very much !

**Comment by Vinnl** [comment]
Allright, I'm going to try - give me a few minutes.

**Comment by Vinnl** [comment]
I contacted you through email as well, but for posterity: there were quite a few new services when regenerating the website.

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

        services/4lnb.json
        services/abc-australia.json
        services/accuweather.json
        services/adobe.json
        services/albine.json
        services/ancestry.json
        services/applits.json
        services/arc-games.json
        services/ask.json
        services/badoo.json
        services/billionsinchange.json
        services/bing.json
        services/bitpay.json
        services/bittorrent.json
        services/bluestacks.json
        services/bodybuilding.json
        services/burning-man.json
        services/bushel.json
        services/canary.json
        services/careerone.json
        services/caringbridge.json
        services/centurylink.json
        services/chromewebstore.json
        services/codeschool.json
        services/coinbase.json
        services/coveredca.json
        services/cox.json
        services/crowdtilt.json
        services/drf.json
        services/easynews.json
        services/educreations.json
        services/elance.json
        services/em-client.json
        services/energyhelpline.json
        services/enjin.json
        services/eve-online.json
        services/fc2.json
        services/feedly.json
        services/fifa-com.json
        services/fitbit.json
        services/flist.json
        services/fotocommunity.json
        services/furaffinity.json
        services/furrymate.json
        services/gitorious.json
        services/gittip.json
        services/godaddy.json
        services/google-fiber.json
        services/grasscity.json
        services/grooveshark.json
        services/gumtree.json
        services/huffingtonpost.json
        services/hulu.json
        services/identica.json
        services/inter-chat.json
        services/isis-mobile-wallet.json
        services/ixquick.json
        services/jawbone.json
        services/jobvite.json
        services/kickstarter.json
        services/kik-messenger.json
        services/kilu.json
        services/king.json
        services/kixeye.json
        services/koding.json
        services/kongregate.json
        services/leagueoflegends.json
        services/letsencrypt.json
        services/lfichier.json
        services/looki.json
        services/meetup.json
        services/minuscom.json
        services/mitfahrgelegenheit.json
        services/mobilitytrip.json
        services/mondosol.json
        services/mozilla.json
        services/multiple.json
        services/nanowrimo.json
        services/npr.json
        services/nxpay.json
        services/onlive.json
        services/pagebin.json
        services/path.json
        services/piazzacom.json
        services/pixabay.json
        services/plenti.json
        services/pocket.json
        services/proboards.json
        services/rac.json
        services/researchgate.json
        services/restream.json
        services/runtastic.json
        services/scrubly.json
        services/sharemylesson.json
        services/sharetube.json
        services/simplehitcounter.json
        services/sony.json
        services/sourceforge.json
        services/sprint.json
        services/stackoverflow.json
        services/startpage.json
        services/strangertickets.json
        services/stumble-upon.json
        services/styleseat.json
        services/symantec.json
        services/taco.json
        services/tes-connect.json
        services/themeforest.json
        services/tidyio.json
        services/tinkercad.json
        services/tmobile.json
        services/typeform.json
        services/undefined.json
        services/vocaroo.json
        services/vudu.json
        services/waveapps.json
        services/weibo.json
        services/whatpulse.json
        services/xapo.json
        services/xfinity.json
        services/xiaomi.json
        services/yammer.json
        services/yourepeat.json
        services/youropinion.json
        services/zenfolio.json
        services/zoominfo.json

I'm assuming these were recently added, but just hadn't been committed yet? (Although `services/undefined.json` looks suspicious.)

Since I haven't had a reply from you yet, the campaign starting in a few hours, and my not being sure how long the deployment is going to take, I'm going to push it now and hope for the best :) If it ends up problematic, I should hopefully have enough time to properly revert it as well.

**Comment by piks3l** [comment]
Yeah no problem ! Thanks. Don't worry about the db, we can import it easily

**Comment by Vinnl** [comment]
It's live! And I think everything works as expected, but do double-check to be sure.

**Comment by piks3l** [comment]
Amazing! Thanks you very much, look neat. I'll have other PR to make for this, for example to feature our video in it. Is it okay if I ask you again ?

**Comment by Vinnl** [comment]
Sure :)

**Comment by michielbdejong3** [comment]
Thanks! Yes, I recently added a lot of services, so probably those hadn't been deployed yet. I'll look into the service called `'undefined'` :)

**Pull request merged**
